name: device-screenshots

on:
  issue_comment:
    types: [created]

jobs:
  sanitize:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'thenonexistentguy'
    permissions:
      pull-requests: write
    steps:
      - name: Debug event data
        run: echo "${{ toJson(github.event) }}"
